# Simple workflow for deploying static content to GitHub Pages
name: Build docs

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-24.04
    env:
      PUBLISH_DIR: ./_build/html

    steps:
      # checkout the repository
      - uses: actions/checkout@v5

      # setup Python
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --extra docs

      - name: Build docs
        run: uv run jupyter book build .

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
