# Simple workflow for deploying static content to GitHub Pages
name: Reproduce results

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:


jobs:
  run:
    runs-on: ubuntu-22.04
    env:
      # Directory that will be published on github pages
      DATAPATH: ./artifacts/data/data.json
      FIGDIR: ./artifacts/figures
      RESULTDIR: ./artifacts/results

    steps:
      - uses: actions/checkout@v5

    # setup Python
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync

      - name: Run pre-processing
        run: uv run python3 code/pre_processing.py --datapath=${{ env.DATAPATH }}

      - name: Run simulation
        run: uv run python3 code/run_all.py --resultdir=${{ env.RESULTDIR }}

      - name: Postprocess
        run: uv run python3 code/postprocess.py --resultdir=${{ env.RESULTDIR }} --datapath=${{ env.DATAPATH }} --figdir=${{ env.FIGDIR }}

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v5
        with:
          path: ./artifacts
          if-no-files-found: error
